# Generated by Django 4.2.7 on 2023-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
