# Generated by Django 4.2.7 on 2023-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_alter_payment_session_id_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
