# Generated by Django 4.2.7 on 2023-11-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_alter_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
