# Generated by Django 4.2.7 on 2023-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0008_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PAID", "Paid"),
                    ("PENDING", "Pending"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=7,
            ),
        ),
    ]
