# Generated by Django 4.2.7 on 2023-11-29 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0009_alter_payment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-borrow_date"]},
        ),
    ]
